#!/usr/bin/env bash

# Follow instructions here: https://docs.docker.com/config/containers/resource_constraints/#access-an-nvidia-gpu
docker run \
  -it \
  --gpus all \
  -w "$PWD" \
  --user "$(id -u):$(id -g)" \
  --ipc=host \
  -v "${HOME}:${HOME}" \
  -v /media/cache:/media/cache:ro \
  -v /etc/hostname:/etc/hostname:ro \
  -v /etc/localtime:/etc/localtime:ro \
  larynx2-train \
  "$@"
